language: go

go:
  - 1.x
  - master

before_script:
  - go get github.com/tools/godep
  - make restore -C ./httpworker
  - make restore -C ./rssworker
  - make restore -C ./logworker
  - make restore -C ./ircworker

script:
  - make test
